.TH "lib/my/src/str Directory Reference" 3 "Wed Jan 7 2015" "Version 1.0" "myhs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/src/str Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBget_next_line\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_putnstr\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_spe_in_tab\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strcmp\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strcpy\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strdup\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strlen\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strncmp\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strncpy\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strndup\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strnscpy\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_strnsdup\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_word_in_tab\&.c\fP"
.br
.in -1c
