.TH "lib/my/src/printf Directory Reference" 3 "Wed Jan 7 2015" "Version 1.0" "myhs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/src/printf Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcase_printf_part1\&.c\fP"
.br
.ti -1c
.RI "file \fBcase_printf_part2\&.c\fP"
.br
.ti -1c
.RI "file \fBcase_printf_part3\&.c\fP"
.br
.ti -1c
.RI "file \fBcase_printf_part4\&.c\fP"
.br
.ti -1c
.RI "file \fBconvert_base_deci\&.c\fP"
.br
.ti -1c
.RI "file \fBconvert_base_deci_part2\&.c\fP"
.br
.ti -1c
.RI "file \fBconvert_base_deci_part3\&.c\fP"
.br
.ti -1c
.RI "file \fBconvert_base_deci_part4\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_printf\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_putchar\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_putnbr\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_putstr\&.c\fP"
.br
.ti -1c
.RI "file \fBmy_unputnbr\&.c\fP"
.br
.in -1c
