lib/my/src/printf/case_printf_part2.c
NAME
lib/my/src/printf/case_printf_part2.c -
SYNOPSIS
#include 'my.h'
Functions
int case_b (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_di (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_o (void *argv, t_index *s, const char *format, const t_struc *tab)
int x_case (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_u (void *argv, t_index *s, const char *format, const t_struc *tab)
Function Documentation
int case_b (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 13 of file case_printf_part2.c.
References convert_base_deci_2().
Referenced by my_printf().
{
  long n;
  int r;
  (void)*s;
  (void)*format;
  (void)*tab;
  n = (long)argv;
  r = convert_base_deci_2((int)n);
  return (r);
}
int case_di (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 27 of file case_printf_part2.c.
References my_lputnbr(), my_putnbrs(), s_index::nbr, and s_index::p.
Referenced by my_printf().
{
  long n;
  int r;
  (void)tab;
  (void)format;
  n = (long)argv;
  if (s->p == 2)
    r = my_lputnbr(n);
  else
    r = my_putnbrs((int)n, s->p, s->nbr);
  s->p = 0;
  return (r);
}
int case_o (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 44 of file case_printf_part2.c.
References convert_base_deci_8_lunint(), convert_base_deci_8_unint(), and s_index::p.
Referenced by my_printf().
{
  long n;
  int r;
  (void)*tab;
  (void)*s;
  (void)*format;
  n = (long)argv;
  if (s->p == 2)
    convert_base_deci_8_lunint((long unsigned int)n);
  else
    r = convert_base_deci_8_unint((unsigned int)n);
  return (r);
  s->p = 0;
}
int case_u (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 79 of file case_printf_part2.c.
References my_lunputnbr(), my_unputnbrs(), s_index::nbr, and s_index::p.
Referenced by my_printf().
{
  long n;
  int r;
  (void)*s;
  (void)*tab;
  (void)*format;
  n = (long)argv;
  if (s->p == 2)
    my_lunputnbr((long unsigned int)n);
  else
    r = my_unputnbrs((unsigned int)n, s->p, s->nbr);
  s->p = 0;
  return (r);
}
int x_case (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 62 of file case_printf_part2.c.
References convert_base_deci_16_lun(), convert_base_deci_16_un(), and s_index::p.
Referenced by my_printf().
{
  long n;
  int r;
  (void)*tab;
  (void)*s;
  (void)*format;
  n = (long)argv;
  if (s->p == 2)
    r = convert_base_deci_16_lun((long unsigned int)n, "0123456789ABCDEF");
  else
    r = convert_base_deci_16_un((unsigned int)n, "0123456789ABCDEF");
  return (r);
}
Author
Generated automatically by Doxygen for myhs from the source code.