lib/my/src/printf/case_printf_part1.c
NAME
lib/my/src/printf/case_printf_part1.c -
SYNOPSIS
#include 'my.h'
Functions
int s_putstr (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_p (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_x (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_c (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_s (void *argv, t_index *s, const char *format, const t_struc *tab)
Function Documentation
int case_c (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 66 of file case_printf_part1.c.
References my_putchar().
Referenced by my_printf().
{
  long c;
  (void)*s;
  (void)*format;
  (void)*tab;
  c = (long)argv;
  my_putchar((char)c);
  return (1);
}
int case_p (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 35 of file case_printf_part1.c.
References convert_base_deci_16().
Referenced by my_printf().
{
  long n;
  int r;
  (void)*s;
  (void)*format;
  (void)*tab;
  n = (long)argv;
  r = convert_base_deci_16(n, "0123456789abcdef");
  return (r);
}
int case_s (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 79 of file case_printf_part1.c.
References my_putstr().
Referenced by my_printf().
{
  long *str;
  int r;
  str = argv;
  (void)*format;
  (void)*tab;
  if (str == 0)
    {
      my_putstr("(null)");
      return (6);
    }
  (void)*s;
  r = my_putstr((char *)str);
  return (r);
}
int case_x (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 49 of file case_printf_part1.c.
References convert_base_deci_16_lun(), convert_base_deci_16_un(), and s_index::p.
Referenced by my_printf().
{
  long n;
  int r;
  (void)*s;
  (void)*format;
  (void)*tab;
  n = (long)argv;
  if (s->p == 2)
    r = convert_base_deci_16_lun((long unsigned int)n, "0123456789abcdef");
  else
    r = convert_base_deci_16_un((unsigned int)n, "0123456789abcdef");
  return (r);
}
int s_putstr (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 13 of file case_printf_part1.c.
References convert_base_deci_octal(), and my_putchar().
Referenced by my_printf().
{
  int i;
  char *str;
  (void)*s;
  (void)*format;
  (void)*tab;
  str = argv;
  i = 0;
  while (str[i])
    {
      if (str[i] < 32 || str[i] >= 127)
    convert_base_deci_octal(str[i], "01234567");
      else
    my_putchar(str[i]);
      i++;
    }
  return (i);
}
Author
Generated automatically by Doxygen for myhs from the source code.