lib/my/src/printf/case_printf_part3.c
NAME
lib/my/src/printf/case_printf_part3.c -
SYNOPSIS
#include 'my.h'
Functions
int case_pres (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_sharp2 (t_index *s, const char *format, int i, const t_struc *tab)
int case_sharp (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_zero (void *argv, t_index *s, const char *format, const t_struc *tab)
Function Documentation
int case_pres (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 13 of file case_printf_part3.c.
References my_putchar().
Referenced by my_printf().
{
  (void)*s;
  (void)*tab;
  (void)argv;
  (void)*format;
  my_putchar('%');
  return (1);
}
int case_sharp (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 42 of file case_printf_part3.c.
References case_sharp2(), s_index::i, s_index::n, and s_struc::ptr_tab.
Referenced by my_printf().
{
  int i;
  int ret;
  i = 0;
  ret = 0;
  if (format[s->i + 1] == 'x' || format[s->i + 1] == 'X'
      || format[s->i + 1] == 'o')
    {
      s->n = 0;
      i = case_sharp2(s, format, i, tab);
      ret = i;
      i = (*tab[s->n].ptr_tab)(argv, s, format, tab);
      i = i + ret;
      s->i++;
    }
  return (i);
}
int case_sharp2 (t_index *s, const char *format, inti, const t_struc *tab)
Definition at line 24 of file case_printf_part3.c.
References s_struc::c, s_index::i, my_putchar(), my_putstr(), and s_index::n.
Referenced by case_sharp().
{
  if (format[s->i + 1] == 'x' || format[s->i + 1] == 'X')
    {
      my_putstr("0x");
      i = i + 2;
    }
  else if (format[s->i + 1] == 'o')
    {
      my_putchar('0');
      i = i + 1;
    }
  while (tab[s->n].c != format[s->i + 1])
    s->n++;
  return (i);
}
int case_zero (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 63 of file case_printf_part3.c.
References s_struc::c, s_index::i, s_index::n, s_index::nbr, s_index::p, and s_struc::ptr_tab.
Referenced by my_printf().
{
  int i;
  s->nbr = 0;
  i = 0;
  while (format[s->i + 1] >= '0' && format[s->i + 1] <= '9')
    {
      s->nbr = s->nbr * 10 + format[s->i + 1] - '0';
      s->i++;
    }
  if (format[s->i + 1] == 'x' || format[s->i + 1] == 'X'
      || format[s->i + 1] == 'o' || format[s->i + 1] == 'u'
      || format[s->i + 1] == 'd' || format[s->i + 1] == 'i')
    {
      s->p = 1;
      s->n = 0;
      while (tab[s->n].c != format[s->i + 1])
    s->n++;
      i = (*tab[s->n].ptr_tab)(argv, s, format, tab);
      s->i++;
    }
  return (i);
}
Author
Generated automatically by Doxygen for myhs from the source code.