lib/my/src/printf/convert_base_deci_part2.c
NAME
lib/my/src/printf/convert_base_deci_part2.c -
SYNOPSIS
#include 'my.h'
Functions
int my_strlen (char *str)
int my_rev_int_tab_long (char *tab, long i)
void my_rev_int_tab_un (char *tab, long i)
void my_rev_int_tab (int *tab, int i)
Function Documentation
void my_rev_int_tab (int *tab, inti)
Definition at line 54 of file convert_base_deci_part2.c.
References my_putnbr().
Referenced by convert_base_deci_2().
{
  i--;
  while (i >= 0)
    {
      my_putnbr(tab[i]);
      i--;
    }
}
int my_rev_int_tab_long (char *tab, longi)
Definition at line 23 of file convert_base_deci_part2.c.
References my_putchar(), and my_putstr().
Referenced by convert_base_deci_16().
{
  int r;
  i--;
  if (tab[i] == 48 && tab[i + 1] == '\0')
    {
      my_putstr("(nil)");
      return (5);
    }
  my_putstr("0x");
  r = 2;
  while (i >= 0)
    {
      my_putchar(tab[i]);
      i--;
      r++;
    }
  return (r);
}
void my_rev_int_tab_un (char *tab, longi)
Definition at line 44 of file convert_base_deci_part2.c.
References my_putchar().
Referenced by convert_base_deci_16_lun(), and convert_base_deci_16_un().
{
  i--;
  while (i >= 0)
    {
      my_putchar(tab[i]);
      i--;
    }
}
int my_strlen (char *str)
Definition at line 13 of file convert_base_deci_part2.c.
Referenced by convert_base_deci_octal(), my_putnstr(), my_strdup(), my_strndup(), and my_strnsdup().
{
  int i;
  i = 0;
  while (str[i])
    i++;
  return (i);
}
Author
Generated automatically by Doxygen for myhs from the source code.