lib/my/src/printf/convert_base_deci_part4.c
NAME
lib/my/src/printf/convert_base_deci_part4.c -
SYNOPSIS
#include <stdlib.h>
#include 'my.h'
Functions
int convert_base_deci_16_lun (long unsigned int nb, char *str)
void my_rev_lunint_tab (long unsigned int *tab, int i)
int convert_base_deci_8_lunint (long unsigned int nb)
Function Documentation
int convert_base_deci_16_lun (long unsigned intnb, char *str)
Definition at line 14 of file convert_base_deci_part4.c.
References my_rev_int_tab_un().
Referenced by case_x(), and x_case().
{
  int base;
  long unsigned int res;
  char *tab;
  unsigned int i;
  tab = malloc(sizeof(*tab) * 20 + 1);
  if (tab == NULL)
    return (1);
  res = 1;
  i = 0;
  base = 16;
  while (res != 0)
    {
      res = nb / base;
      tab[i] = nb % base;
      tab[i] = str[nb % base];
      i++;
      nb = res;
    }
  tab[i] = '\0';
  my_rev_int_tab_un(tab, i);
  free(tab);
  return (i);
}
int convert_base_deci_8_lunint (long unsigned intnb)
Definition at line 51 of file convert_base_deci_part4.c.
References my_rev_lunint_tab().
Referenced by case_o().
{
  int base;
  long unsigned int res;
  long unsigned int *tab;
  int i;
  tab = malloc(sizeof(*tab) * 16 + 1);
  if (tab == NULL)
    return (1);
  res = 1;
  i = 0;
  base = 8;
  while (res != 0)
    {
      res = nb / base;
      tab[i] = nb % base;
      i++;
      nb = res;
    }
  tab[i] = '\0';
  my_rev_lunint_tab(tab, i);
  free(tab);
  return (i);
}
void my_rev_lunint_tab (long unsigned int *tab, inti)
Definition at line 41 of file convert_base_deci_part4.c.
References my_lunputnbr().
Referenced by convert_base_deci_8_lunint().
{
  i--;
  while (i >= 0)
    {
      my_lunputnbr(tab[i]);
      i--;
    }
}
Author
Generated automatically by Doxygen for myhs from the source code.