lib/my/src/printf/convert_base_deci_part3.c
NAME
lib/my/src/printf/convert_base_deci_part3.c -
SYNOPSIS
#include <stdlib.h>
#include 'my.h'
Functions
void my_rev_unint_tab (unsigned int *tab, int i)
void my_rev_caract_nimpr (int *tab, int i)
int my_nb_stack (char n)
int convert_base_deci_2 (int nb)
int convert_base_deci_octal (char strnb, char *str)
Function Documentation
int convert_base_deci_2 (intnb)
Definition at line 48 of file convert_base_deci_part3.c.
References my_rev_int_tab().
Referenced by case_b().
{
  int base;
  int res;
  int *tab;
  int i;
  if (nb < 0)
    nb = - nb;
  tab = malloc(sizeof(*tab) * 16 + 1);
  if (tab == NULL)
    return (1);
  res = 1;
  i = 0;
  base = 2;
  while (res != 0)
    {
      res = nb / base;
      tab[i] = nb % base;
      i++;
      nb = res;
    }
  my_rev_int_tab(tab, i);
  free(tab);
  return (i);
}
int convert_base_deci_octal (charstrnb, char *str)
Definition at line 75 of file convert_base_deci_part3.c.
References my_rev_caract_nimpr(), and my_strlen().
Referenced by s_putstr().
{
  int base;
  int res;
  int *tab;
  int i;
  int nb;
  tab = malloc(sizeof(*tab) * 16 + 1);
  if (tab == NULL)
    return (1);
  nb = strnb;
  res = 1;
  i = 0;
  base = my_strlen(str);
  while (res != 0)
    {
      res = nb / base;
      tab[i] = str[nb % base];
      i++;
      nb = res;
    }
  tab[i] = '\0';
  my_rev_caract_nimpr(tab, i);
  free(tab);
  return (i);
}
int my_nb_stack (charn)
Definition at line 39 of file convert_base_deci_part3.c.
{
  int nb;
  nb = 0;
  nb = nb * 10 + n;
  return (nb);
}
void my_rev_caract_nimpr (int *tab, inti)
Definition at line 24 of file convert_base_deci_part3.c.
References my_putchar(), and my_putstr().
Referenced by convert_base_deci_octal().
{
  i--;
  my_putchar(92);
  if (i == 0)
    my_putstr("00");
  if (i == 1)
    my_putchar('0');
  while (i >= 0)
    {
      my_putchar(tab[i]);
      i--;
    }
}
void my_rev_unint_tab (unsigned int *tab, inti)
Definition at line 14 of file convert_base_deci_part3.c.
References my_unputnbr().
Referenced by convert_base_deci_8_unint().
{
  i--;
  while (i >= 0)
    {
      my_unputnbr(tab[i]);
      i--;
    }
}
Author
Generated automatically by Doxygen for myhs from the source code.