lib/my/src/printf/convert_base_deci.c
NAME
lib/my/src/printf/convert_base_deci.c -
SYNOPSIS
#include <stdlib.h>
#include 'my.h'
Functions
int convert_base_deci_8_unint (unsigned int nb)
int convert_base_deci_16_un (unsigned int nb, char *str)
int convert_base_deci_16 (long nb, char *str)
Function Documentation
int convert_base_deci_16 (longnb, char *str)
Definition at line 67 of file convert_base_deci.c.
References my_rev_int_tab_long().
Referenced by case_p().
{
  int base;
  long res;
  char *tab;
  long i;
  tab = malloc(sizeof(*tab) * 32 + 1);
  if (tab == NULL)
    return (1);
  res = 1;
  i = 0;
  base = 16;
  while (res != 0)
    {
      res = nb / base;
      tab[i] = str[nb % base];
      i++;
      nb = res;
    }
  tab[i] = '\0';
  i = my_rev_int_tab_long(tab, i);
  free(tab);
  return (i);
}
int convert_base_deci_16_un (unsigned intnb, char *str)
Definition at line 40 of file convert_base_deci.c.
References my_rev_int_tab_un().
Referenced by case_x(), and x_case().
{
  int base;
  unsigned int res;
  char *tab;
  unsigned int i;
  tab = malloc(sizeof(*tab) * 16 + 1);
  if (tab == NULL)
    return (1);
  res = 1;
  i = 0;
  base = 16;
  while (res != 0)
    {
      res = nb / base;
      tab[i] = nb % base;
      tab[i] = str[nb % base];
      i++;
      nb = res;
    }
  tab[i] = '\0';
  my_rev_int_tab_un(tab, i);
  free(tab);
  return (i);
}
int convert_base_deci_8_unint (unsigned intnb)
Definition at line 14 of file convert_base_deci.c.
References my_rev_unint_tab().
Referenced by case_o().
{
  int base;
  unsigned int res;
  unsigned int *tab;
  int i;
  tab = malloc(sizeof(*tab) * 16 + 1);
  if (tab == NULL)
    return (1);
  res = 1;
  i = 0;
  base = 8;
  while (res != 0)
    {
      res = nb / base;
      tab[i] = nb % base;
      i++;
      nb = res;
    }
  tab[i] = '\0';
  my_rev_unint_tab(tab, i);
  free(tab);
  return (i);
}
Author
Generated automatically by Doxygen for myhs from the source code.