lib/my/src/str/get_next_line.c
NAME
lib/my/src/str/get_next_line.c -
SYNOPSIS
#include <unistd.h>
#include <stdlib.h>
#include 'my.h'
Functions
void where_my_buff_end (char *statbuffer, char *stockstat, int j)
void my_gstrcpy (char *buffer, char *stockstat, t_getline *s, char *dest)
char * stat_in_buff (char *statbuffer, char *buffer, t_getline *s, char *dest)
char * get_next_line (const int fd)
Function Documentation
char* get_next_line (const intfd)
Definition at line 81 of file get_next_line.c.
References s_getline::buffer, s_getline::dest, s_getline::i, s_getline::ret, SIZE_OF_READ, stat_in_buff(), and s_getline::stop.
Referenced by minishell1().
{
  static char statbuffer[SIZE_OF_READ + 1];
  t_getline s;
  s.i = 1;
  s.stop = 0;
  while (s.stop == 0)
    {
      if ((s.buffer = malloc(SIZE_OF_READ * s.i + SIZE_OF_READ)) == NULL)
    return (NULL);
      if ((s.ret = read(fd, statbuffer, SIZE_OF_READ)) == - 1)
    return (NULL);
      statbuffer[s.ret] = '\0';
      s.buffer = stat_in_buff(statbuffer, s.buffer, &s, s.dest);
      if (s.i != 1)
    free(s.dest);
      if (s.ret == 0)
    {
      close(fd);
      return (s.buffer);
    }
      s.dest = s.buffer;
      s.i++;
    }
  return (s.buffer);
}
void my_gstrcpy (char *buffer, char *stockstat, t_getline *s, char *dest)
Definition at line 29 of file get_next_line.c.
References s_getline::i, s_getline::s, and SIZE_OF_READ.
Referenced by stat_in_buff().
{
  int i;
  i = 0;
  while (stockstat[s->s])
    {
      buffer[s->s] = stockstat[i];
      s->s++;
      i++;
    }
  i = 0;
  while (i != SIZE_OF_READ)
    {
      stockstat[i] = '\0';
      i++;
    }
  i = 0;
  while (i != (s->i - 1) * SIZE_OF_READ)
    {
      buffer[s->s] = dest[i];
      i++;
      s->s++;
    }
}
char* stat_in_buff (char *statbuffer, char *buffer, t_getline *s, char *dest)
Definition at line 55 of file get_next_line.c.
References my_gstrcpy(), s_getline::s, SIZE_OF_READ, s_getline::stop, and where_my_buff_end().
Referenced by get_next_line().
{
  int j;
  static char stockstat[SIZE_OF_READ + 1];
  j = 0;
  s->s = 0;
  my_gstrcpy(buffer, stockstat, s, dest);
  while (j != SIZE_OF_READ && s->stop != 1)
    {
      buffer[s->s] = statbuffer[j];
      if (buffer[s->s] == '\n')
    {
      s->stop = 1;
      where_my_buff_end(statbuffer, stockstat, j);
      buffer[s->s] = '\0';
    }
      else
    buffer[s->s + 1] = '\0';
      s->s++;
      j++;
    }
  return (buffer);
}
void where_my_buff_end (char *statbuffer, char *stockstat, intj)
Definition at line 15 of file get_next_line.c.
Referenced by stat_in_buff().
{
  int i;
  i = 0;
  while (statbuffer[j + 1])
    {
      stockstat[i] = statbuffer[j + 1];
      i++;
      j++;
    }
  stockstat[i] = '\0';
}
Author
Generated automatically by Doxygen for myhs from the source code.