include/my.h
NAME
include/my.h -
SYNOPSIS
#include <stdarg.h>
Data Structures
struct s_index
struct s_struc
struct s_win
struct s_getline
Macros
#define SIZE_OF_READ 1
Typedefs
typedef struct s_index t_index
typedef struct s_struc t_struc
typedef struct s_win t_win
typedef struct s_getline t_getline
Functions
int my_strcmp (char *a, char *b)
int my_strlen (char *str)
char * my_strcpy (char *dest, char *src)
char * my_strdup (char *src)
char * get_next_line (const int fd)
char ** my_spe_in_tab (char *str, char sep)
int my_strncmp (char *a, char *b, int nb)
void my_putnstr (char *str, int nb)
char * my_strndup (char *src, int nb)
char * my_strncpy (char *dest, char *src, int nb)
char * my_strnsdup (char *src, int nb)
char * my_strnscpy (char *dest, char *src, int nb)
int my_printf (const char *format,...)
void my_putchar (char c)
int my_putstr (char *str)
int my_putnbr (int nb)
int my_unputnbr (unsigned int nb)
int my_rev_int_tab_long (char *tab, long i)
void my_rev_int_tab_un (char *tab, long i)
void my_rev_int_tab (int *tab, int i)
void my_rev_unint_tab (unsigned int *tab, int i)
void my_rev_caract_nimpr (int *tab, int i)
int my_nb_stack (char n)
int convert_base_deci_2 (int nb)
int convert_base_deci_octal (char strnb, char *str)
int convert_base_deci_8_unint (unsigned int nb)
int convert_base_deci_16_un (unsigned int nb, char *str)
int convert_base_deci_16 (long nb, char *str)
int s_putstr (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_p (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_x (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_c (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_s (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_b (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_di (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_o (void *argv, t_index *s, const char *format, const t_struc *tab)
int x_case (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_u (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_pres (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_sharp (void *argv, t_index *s, const char *format, const t_struc *tab)
int case_sharp2 (t_index *s, const char *format, int i, const t_struc *tab)
int case_zero (void *argv, t_index *s, const char *format, const t_struc *tab)
int my_putnbrnoaffich (int nb)
int my_putnbrs (int nb, int p, int nbr)
int my_unputnbrnoaffich (unsigned int nb)
int my_unputnbrs (unsigned int nb, int p, int nbr)
int case_l (void *argv, t_index *s, const char *format, const t_struc *tab)
int my_lunputnbr (long unsigned int nb)
int my_lputnbr (long int nb)
int convert_base_deci_16_lun (long unsigned int nb, char *str)
void my_rev_lunint_tab (long unsigned int *tab, int i)
int convert_base_deci_8_lunint (long unsigned int nb)
char ** my_word_in_tab (char *str)
char * getbuffer (char *buffer, char *retbuffer)
char * stat_in_buff (char *strtbuffer, char *buffer, t_getline *s, char *dest)
void where_my_buff_end (char *statbuffer, char *stockstat, int j)
void my_gstrcpy (char *buffer, char *stockstat, t_getline *s, char *dest)
Macro Definition Documentation
#define SIZE_OF_READ 1
Definition at line 151 of file my.h.
Referenced by get_next_line(), my_gstrcpy(), and stat_in_buff().
Typedef Documentation
typedef struct s_getline		 t_getline
typedef struct s_index			 t_index
typedef struct s_struc			 t_struc
typedef struct s_win		 t_win
Function Documentation
int case_b (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 13 of file case_printf_part2.c.
References convert_base_deci_2().
Referenced by my_printf().
{
  long n;
  int r;
  (void)*s;
  (void)*format;
  (void)*tab;
  n = (long)argv;
  r = convert_base_deci_2((int)n);
  return (r);
}
int case_c (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 66 of file case_printf_part1.c.
References my_putchar().
Referenced by my_printf().
{
  long c;
  (void)*s;
  (void)*format;
  (void)*tab;
  c = (long)argv;
  my_putchar((char)c);
  return (1);
}
int case_di (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 27 of file case_printf_part2.c.
References my_lputnbr(), my_putnbrs(), s_index::nbr, and s_index::p.
Referenced by my_printf().
{
  long n;
  int r;
  (void)tab;
  (void)format;
  n = (long)argv;
  if (s->p == 2)
    r = my_lputnbr(n);
  else
    r = my_putnbrs((int)n, s->p, s->nbr);
  s->p = 0;
  return (r);
}
int case_l (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 13 of file case_printf_part4.c.
References s_struc::c, s_index::i, s_index::n, s_index::p, and s_struc::ptr_tab.
Referenced by my_printf().
{
  int i;
  i = 0;
  if (format[s->i + 1] == 'x' || format[s->i + 1] == 'X'
      || format[s->i + 1] == 'o' || format[s->i + 1] == 'd'
      || format[s->i + 1] == 'i' || format[s->i + 1] == 'u')
    {
      s->p = 2;
      s->n = 0;
      while (tab[s->n].c != format[s->i + 1])
    s->n++;
      i = (*tab[s->n].ptr_tab)(argv, s, format, tab);
      s->i++;
    }
  return (i);
}
int case_o (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 44 of file case_printf_part2.c.
References convert_base_deci_8_lunint(), convert_base_deci_8_unint(), and s_index::p.
Referenced by my_printf().
{
  long n;
  int r;
  (void)*tab;
  (void)*s;
  (void)*format;
  n = (long)argv;
  if (s->p == 2)
    convert_base_deci_8_lunint((long unsigned int)n);
  else
    r = convert_base_deci_8_unint((unsigned int)n);
  return (r);
  s->p = 0;
}
int case_p (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 35 of file case_printf_part1.c.
References convert_base_deci_16().
Referenced by my_printf().
{
  long n;
  int r;
  (void)*s;
  (void)*format;
  (void)*tab;
  n = (long)argv;
  r = convert_base_deci_16(n, "0123456789abcdef");
  return (r);
}
int case_pres (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 13 of file case_printf_part3.c.
References my_putchar().
Referenced by my_printf().
{
  (void)*s;
  (void)*tab;
  (void)argv;
  (void)*format;
  my_putchar('%');
  return (1);
}
int case_s (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 79 of file case_printf_part1.c.
References my_putstr().
Referenced by my_printf().
{
  long *str;
  int r;
  str = argv;
  (void)*format;
  (void)*tab;
  if (str == 0)
    {
      my_putstr("(null)");
      return (6);
    }
  (void)*s;
  r = my_putstr((char *)str);
  return (r);
}
int case_sharp (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 42 of file case_printf_part3.c.
References case_sharp2(), s_index::i, s_index::n, and s_struc::ptr_tab.
Referenced by my_printf().
{
  int i;
  int ret;
  i = 0;
  ret = 0;
  if (format[s->i + 1] == 'x' || format[s->i + 1] == 'X'
      || format[s->i + 1] == 'o')
    {
      s->n = 0;
      i = case_sharp2(s, format, i, tab);
      ret = i;
      i = (*tab[s->n].ptr_tab)(argv, s, format, tab);
      i = i + ret;
      s->i++;
    }
  return (i);
}
int case_sharp2 (t_index *s, const char *format, inti, const t_struc *tab)
Definition at line 24 of file case_printf_part3.c.
References s_struc::c, s_index::i, my_putchar(), my_putstr(), and s_index::n.
Referenced by case_sharp().
{
  if (format[s->i + 1] == 'x' || format[s->i + 1] == 'X')
    {
      my_putstr("0x");
      i = i + 2;
    }
  else if (format[s->i + 1] == 'o')
    {
      my_putchar('0');
      i = i + 1;
    }
  while (tab[s->n].c != format[s->i + 1])
    s->n++;
  return (i);
}
int case_u (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 79 of file case_printf_part2.c.
References my_lunputnbr(), my_unputnbrs(), s_index::nbr, and s_index::p.
Referenced by my_printf().
{
  long n;
  int r;
  (void)*s;
  (void)*tab;
  (void)*format;
  n = (long)argv;
  if (s->p == 2)
    my_lunputnbr((long unsigned int)n);
  else
    r = my_unputnbrs((unsigned int)n, s->p, s->nbr);
  s->p = 0;
  return (r);
}
int case_x (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 49 of file case_printf_part1.c.
References convert_base_deci_16_lun(), convert_base_deci_16_un(), and s_index::p.
Referenced by my_printf().
{
  long n;
  int r;
  (void)*s;
  (void)*format;
  (void)*tab;
  n = (long)argv;
  if (s->p == 2)
    r = convert_base_deci_16_lun((long unsigned int)n, "0123456789abcdef");
  else
    r = convert_base_deci_16_un((unsigned int)n, "0123456789abcdef");
  return (r);
}
int case_zero (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 63 of file case_printf_part3.c.
References s_struc::c, s_index::i, s_index::n, s_index::nbr, s_index::p, and s_struc::ptr_tab.
Referenced by my_printf().
{
  int i;
  s->nbr = 0;
  i = 0;
  while (format[s->i + 1] >= '0' && format[s->i + 1] <= '9')
    {
      s->nbr = s->nbr * 10 + format[s->i + 1] - '0';
      s->i++;
    }
  if (format[s->i + 1] == 'x' || format[s->i + 1] == 'X'
      || format[s->i + 1] == 'o' || format[s->i + 1] == 'u'
      || format[s->i + 1] == 'd' || format[s->i + 1] == 'i')
    {
      s->p = 1;
      s->n = 0;
      while (tab[s->n].c != format[s->i + 1])
    s->n++;
      i = (*tab[s->n].ptr_tab)(argv, s, format, tab);
      s->i++;
    }
  return (i);
}
int convert_base_deci_16 (longnb, char *str)
Definition at line 67 of file convert_base_deci.c.
References my_rev_int_tab_long().
Referenced by case_p().
{
  int base;
  long res;
  char *tab;
  long i;
  tab = malloc(sizeof(*tab) * 32 + 1);
  if (tab == NULL)
    return (1);
  res = 1;
  i = 0;
  base = 16;
  while (res != 0)
    {
      res = nb / base;
      tab[i] = str[nb % base];
      i++;
      nb = res;
    }
  tab[i] = '\0';
  i = my_rev_int_tab_long(tab, i);
  free(tab);
  return (i);
}
int convert_base_deci_16_lun (long unsigned intnb, char *str)
Definition at line 14 of file convert_base_deci_part4.c.
References my_rev_int_tab_un().
Referenced by case_x(), and x_case().
{
  int base;
  long unsigned int res;
  char *tab;
  unsigned int i;
  tab = malloc(sizeof(*tab) * 20 + 1);
  if (tab == NULL)
    return (1);
  res = 1;
  i = 0;
  base = 16;
  while (res != 0)
    {
      res = nb / base;
      tab[i] = nb % base;
      tab[i] = str[nb % base];
      i++;
      nb = res;
    }
  tab[i] = '\0';
  my_rev_int_tab_un(tab, i);
  free(tab);
  return (i);
}
int convert_base_deci_16_un (unsigned intnb, char *str)
Definition at line 40 of file convert_base_deci.c.
References my_rev_int_tab_un().
Referenced by case_x(), and x_case().
{
  int base;
  unsigned int res;
  char *tab;
  unsigned int i;
  tab = malloc(sizeof(*tab) * 16 + 1);
  if (tab == NULL)
    return (1);
  res = 1;
  i = 0;
  base = 16;
  while (res != 0)
    {
      res = nb / base;
      tab[i] = nb % base;
      tab[i] = str[nb % base];
      i++;
      nb = res;
    }
  tab[i] = '\0';
  my_rev_int_tab_un(tab, i);
  free(tab);
  return (i);
}
int convert_base_deci_2 (intnb)
Definition at line 48 of file convert_base_deci_part3.c.
References my_rev_int_tab().
Referenced by case_b().
{
  int base;
  int res;
  int *tab;
  int i;
  if (nb < 0)
    nb = - nb;
  tab = malloc(sizeof(*tab) * 16 + 1);
  if (tab == NULL)
    return (1);
  res = 1;
  i = 0;
  base = 2;
  while (res != 0)
    {
      res = nb / base;
      tab[i] = nb % base;
      i++;
      nb = res;
    }
  my_rev_int_tab(tab, i);
  free(tab);
  return (i);
}
int convert_base_deci_8_lunint (long unsigned intnb)
Definition at line 51 of file convert_base_deci_part4.c.
References my_rev_lunint_tab().
Referenced by case_o().
{
  int base;
  long unsigned int res;
  long unsigned int *tab;
  int i;
  tab = malloc(sizeof(*tab) * 16 + 1);
  if (tab == NULL)
    return (1);
  res = 1;
  i = 0;
  base = 8;
  while (res != 0)
    {
      res = nb / base;
      tab[i] = nb % base;
      i++;
      nb = res;
    }
  tab[i] = '\0';
  my_rev_lunint_tab(tab, i);
  free(tab);
  return (i);
}
int convert_base_deci_8_unint (unsigned intnb)
Definition at line 14 of file convert_base_deci.c.
References my_rev_unint_tab().
Referenced by case_o().
{
  int base;
  unsigned int res;
  unsigned int *tab;
  int i;
  tab = malloc(sizeof(*tab) * 16 + 1);
  if (tab == NULL)
    return (1);
  res = 1;
  i = 0;
  base = 8;
  while (res != 0)
    {
      res = nb / base;
      tab[i] = nb % base;
      i++;
      nb = res;
    }
  tab[i] = '\0';
  my_rev_unint_tab(tab, i);
  free(tab);
  return (i);
}
int convert_base_deci_octal (charstrnb, char *str)
Definition at line 75 of file convert_base_deci_part3.c.
References my_rev_caract_nimpr(), and my_strlen().
Referenced by s_putstr().
{
  int base;
  int res;
  int *tab;
  int i;
  int nb;
  tab = malloc(sizeof(*tab) * 16 + 1);
  if (tab == NULL)
    return (1);
  nb = strnb;
  res = 1;
  i = 0;
  base = my_strlen(str);
  while (res != 0)
    {
      res = nb / base;
      tab[i] = str[nb % base];
      i++;
      nb = res;
    }
  tab[i] = '\0';
  my_rev_caract_nimpr(tab, i);
  free(tab);
  return (i);
}
char * get_next_line (const intfd)
Definition at line 81 of file get_next_line.c.
Referenced by minishell1().
{
  static char statbuffer[SIZE_OF_READ + 1];
  t_getline s;
  s.i = 1;
  s.stop = 0;
  while (s.stop == 0)
    {
      if ((s.buffer = malloc(SIZE_OF_READ * s.i + SIZE_OF_READ)) == NULL)
    return (NULL);
      if ((s.ret = read(fd, statbuffer, SIZE_OF_READ)) == - 1)
    return (NULL);
      statbuffer[s.ret] = '\0';
      s.buffer = stat_in_buff(statbuffer, s.buffer, &s, s.dest);
      if (s.i != 1)
    free(s.dest);
      if (s.ret == 0)
    {
      close(fd);
      return (s.buffer);
    }
      s.dest = s.buffer;
      s.i++;
    }
  return (s.buffer);
}
char* getbuffer (char *buffer, char *retbuffer)
void my_gstrcpy (char *buffer, char *stockstat, t_getline *s, char *dest)
Definition at line 29 of file get_next_line.c.
References s_getline::i, s_getline::s, and SIZE_OF_READ.
Referenced by stat_in_buff().
{
  int i;
  i = 0;
  while (stockstat[s->s])
    {
      buffer[s->s] = stockstat[i];
      s->s++;
      i++;
    }
  i = 0;
  while (i != SIZE_OF_READ)
    {
      stockstat[i] = '\0';
      i++;
    }
  i = 0;
  while (i != (s->i - 1) * SIZE_OF_READ)
    {
      buffer[s->s] = dest[i];
      i++;
      s->s++;
    }
}
int my_lputnbr (long intnb)
Definition at line 77 of file my_unputnbr.c.
References my_putchar().
Referenced by case_di().
{
  long int div;
  int i;
  i = 0;
  div = 1;
  if (nb < 0)
    {
      my_putchar('-');
      nb = - nb;
      i++;
    }
  while (nb / (div * 10) > 0)
    div = div * 10;
  while (div != 0)
    {
      if (div == 1)
    my_putchar(nb % 10 + 48);
      else
    my_putchar(nb / div + 48);
      i++;
      nb = nb % div;
      div = div / 10;
    }
  return (i);
}
int my_lunputnbr (long unsigned intnb)
Definition at line 91 of file my_putnbr.c.
References my_putchar().
Referenced by case_u(), and my_rev_lunint_tab().
{
  long int div;
  int i;
  i = 0;
  div = 1;
  while (nb / (div * 10) > 0)
    div = div * 10;
  while (div != 0)
    {
      if (div == 1)
        my_putchar(nb % 10 + 48);
      else
        my_putchar(nb / div + 48);
      i++;
      nb = nb % div;
      div = div / 10;
    }
  return (i);
}
int my_nb_stack (charn)
Definition at line 39 of file convert_base_deci_part3.c.
{
  int nb;
  nb = 0;
  nb = nb * 10 + n;
  return (nb);
}
int my_printf (const char *format, ...)
Definition at line 57 of file my_printf.c.
References case_b(), case_c(), case_di(), case_l(), case_o(), case_p(), case_pres(), case_s(), case_sharp(), case_u(), case_x(), case_zero(), s_index::i, my_printf2(), s_index::p, s_index::r, s_putstr(), and x_case().
Referenced by my_aff_env().
{
  va_list ap;
  t_index s;
  static const t_struc tab[] = { { 's', &case_s }, { 'p', &case_p },
                  { 'd', &case_di },
              { 'b', &case_b }, { 'x', &case_x }, { 'S', &s_putstr },
              { 'X', &x_case }, { 'u', &case_u }, { 'i', &case_di },
              { 'o', &case_o }, { 'c', &case_c }, { '%', &case_pres },
              { '#', &case_sharp }, { '0', &case_zero }, { 'l', &case_l } };
  s.i = 0;
  s.r = 0;
  s.p = 0;
  va_start(ap, format);
  my_printf2(format, ap, &s, tab);
  va_end(ap);
  return (s.r);
}
void my_putchar (charc)
Definition at line 14 of file my_putchar.c.
Referenced by case_c(), case_pres(), case_sharp2(), my_find_pwd(), my_lputnbr(), my_lunputnbr(), my_printf2(), my_prompt(), my_putnbr(), my_putnbrnoaffich(), my_putnbrs(), my_putnstr(), my_putstr(), my_rev_caract_nimpr(), my_rev_int_tab_long(), my_rev_int_tab_un(), my_unputnbr(), my_unputnbrs(), and s_putstr().
{
  write(1, &c, 1);
}
int my_putnbr (intnb)
Definition at line 13 of file my_putnbr.c.
References my_putchar().
Referenced by my_prompt(), my_putnbrs(), and my_rev_int_tab().
{
  int div;
  int i;
  i = 0;
  div = 1;
  if (nb < 0)
    {
      my_putchar('-');
      nb = - nb;
      i++;
    }
  while (div < 1000000000 && nb / (div * 10) > 0)
    div = div * 10;
  while (div != 0)
    {
      if (div == 1)
    my_putchar(nb % 10 + 48);
      else
    my_putchar(nb / div + 48);
      i++;
      nb = nb % div;
      div = div / 10;
    }
  return (i);
}
int my_putnbrnoaffich (intnb)
Definition at line 41 of file my_putnbr.c.
References my_putchar().
Referenced by my_putnbrs().
{
  int div;
  int i;
  i = 0;
  div = 1;
  if (nb < 0)
    {
      my_putchar('-');
      nb = - nb;
      i++;
    }
  while (div < 1000000000 && nb / (div * 10) > 0)
    div = div * 10;
  while (div != 0)
    {
      nb = nb % div;
      div = div / 10;
      i++;
    }
  return (i);
}
int my_putnbrs (intnb, intp, intnbr)
Definition at line 65 of file my_putnbr.c.
References my_putchar(), my_putnbr(), and my_putnbrnoaffich().
Referenced by case_di().
{
  int i;
  int ret;
  int r;
  r = 0;
  ret = 0;
  if (p == 1)
    {
      i = my_putnbrnoaffich(nb);
      if (nb < 0)
    nb = - nb;
      while (nbr > i)
    {
      my_putchar('0');
      nbr--;
      r++;
    }
    }
  ret = r;
  r = my_putnbr(nb);
  r = ret + r;
  return (r);
}
void my_putnstr (char *str, intnb)
Definition at line 13 of file my_putnstr.c.
References my_putchar(), and my_strlen().
Referenced by my_find_pwd().
{
  int i;
  i = nb;
  if (nb >= my_strlen(str))
    return ;
  while (str[i])
    {
      my_putchar(str[i]);
      i++;
    }
}
int my_putstr (char *str)
Definition at line 13 of file my_putstr.c.
References my_putchar().
Referenced by case_s(), case_sharp2(), case_unsetenv(), minishell1(), my_find_pwd(), my_prompt(), my_rev_caract_nimpr(), my_rev_int_tab_long(), and my_unsetenv().
{
  int i;
  i = 0;
  while (str[i])
    {
      my_putchar(str[i]);
      i++;
    }
  return (i);
}
void my_rev_caract_nimpr (int *tab, inti)
Definition at line 24 of file convert_base_deci_part3.c.
References my_putchar(), and my_putstr().
Referenced by convert_base_deci_octal().
{
  i--;
  my_putchar(92);
  if (i == 0)
    my_putstr("00");
  if (i == 1)
    my_putchar('0');
  while (i >= 0)
    {
      my_putchar(tab[i]);
      i--;
    }
}
void my_rev_int_tab (int *tab, inti)
Definition at line 54 of file convert_base_deci_part2.c.
References my_putnbr().
Referenced by convert_base_deci_2().
{
  i--;
  while (i >= 0)
    {
      my_putnbr(tab[i]);
      i--;
    }
}
int my_rev_int_tab_long (char *tab, longi)
Definition at line 23 of file convert_base_deci_part2.c.
References my_putchar(), and my_putstr().
Referenced by convert_base_deci_16().
{
  int r;
  i--;
  if (tab[i] == 48 && tab[i + 1] == '\0')
    {
      my_putstr("(nil)");
      return (5);
    }
  my_putstr("0x");
  r = 2;
  while (i >= 0)
    {
      my_putchar(tab[i]);
      i--;
      r++;
    }
  return (r);
}
void my_rev_int_tab_un (char *tab, longi)
Definition at line 44 of file convert_base_deci_part2.c.
References my_putchar().
Referenced by convert_base_deci_16_lun(), and convert_base_deci_16_un().
{
  i--;
  while (i >= 0)
    {
      my_putchar(tab[i]);
      i--;
    }
}
void my_rev_lunint_tab (long unsigned int *tab, inti)
Definition at line 41 of file convert_base_deci_part4.c.
References my_lunputnbr().
Referenced by convert_base_deci_8_lunint().
{
  i--;
  while (i >= 0)
    {
      my_lunputnbr(tab[i]);
      i--;
    }
}
void my_rev_unint_tab (unsigned int *tab, inti)
Definition at line 14 of file convert_base_deci_part3.c.
References my_unputnbr().
Referenced by convert_base_deci_8_unint().
{
  i--;
  while (i >= 0)
    {
      my_unputnbr(tab[i]);
      i--;
    }
}
char** my_spe_in_tab (char *str, charsep)
Definition at line 83 of file my_spe_in_tab.c.
References s_win::i, s_win::j, my_word_in_tab_base(), s_win::nb, and s_win::word.
{
  int i;
  int word;
  t_win struc;
  i = 0;
  word = 1;
  struc.j = 0;
  struc.i = 0;
  struc.nb = 0;
  while (str[i])
    {
      if (str[i] == sep)
        {
          i++;
          word++;
          while (str[i] == sep)
            i++;
        }
      else
        i++;
    }
  struc.word = word;
  return (my_word_in_tab_base(str, &struc, sep));
}
int my_strcmp (char *a, char *b)
Definition at line 13 of file my_strcmp.c.
Referenced by case_unsetenv(), and minishell1().
{
  while (((*a) != '\0' && (*b) != '\0'))
    {
      if (*(a) == *(b))
        {
          a++;
          b++;
        }
      else
        break ;
    }
  return ((int) ((*a) - (*b)));
}
char* my_strcpy (char *dest, char *src)
Definition at line 13 of file my_strcpy.c.
Referenced by my_strdup().
{
  char *dest_addr;
  dest_addr = dest;
  while ((*src) != '\0')
    {
      (*dest) = (*src);
      dest++;
      src++;
    }
  *dest = '\0';
  return (dest_addr);
}
char* my_strdup (char *src)
Definition at line 14 of file my_strdup.c.
References my_strcpy(), and my_strlen().
{
  char *new_str;
  int size;
  size = my_strlen(src);
  new_str = malloc(sizeof(char) * size + 1);
  if (new_str == 0)
    return (0);
  my_strcpy(new_str, src);
  return (new_str);
}
int my_strlen (char *str)
Definition at line 11 of file my_strlen.c.
Referenced by convert_base_deci_octal(), my_putnstr(), my_strdup(), my_strndup(), and my_strnsdup().
{
  int i;
  i = 0;
  while (str[i])
    ++i;
  return (i);
}
int my_strncmp (char *a, char *b, intnb)
Definition at line 11 of file my_strncmp.c.
Referenced by case_unsetenv(), my_find_pwd(), and my_unsetenv().
{
  int i;
  i = 0;
  while (a[i] != '\0' && b[i] != '\0' && i != nb)
    {
      if (a[i] == b[i])
    i++;
      else
    return (1);
    }
  return (0);
}
char* my_strncpy (char *dest, char *src, intnb)
Definition at line 13 of file my_strncpy.c.
Referenced by my_strndup().
{
  int i;
  i = 0;
  while (src[i] != '\0' && i != nb)
    {
      dest[i] = src[i];
      i++;
    }
  dest[i] = '\0';
  return (dest);
}
char* my_strndup (char *src, intnb)
Definition at line 14 of file my_strndup.c.
References my_strlen(), and my_strncpy().
{
  char *new_str;
  int size;
  size = my_strlen(src);
  new_str = malloc(sizeof(char) * size + 1);
  if (new_str == 0)
    return (0);
  my_strncpy(new_str, src, nb);
  return (new_str);
}
char* my_strnscpy (char *dest, char *src, intnb)
Definition at line 13 of file my_strnscpy.c.
Referenced by my_strnsdup().
{
  int i;
  int j;
  j = 0;
  i = nb;
  while (src[i] != '\0')
    {
      dest[j] = src[i];
      i++;
      j++;
    }
  dest[j] = '\0';
  return (dest);
}
char* my_strnsdup (char *src, intnb)
Definition at line 14 of file my_strnsdup.c.
References my_strlen(), and my_strnscpy().
Referenced by case_unsetenv().
{
  char *new_str;
  int size;
  size = my_strlen(src);
  new_str = malloc(sizeof(char) * size + 1);
  if (new_str == 0)
    return (0);
  my_strnscpy(new_str, src, nb);
  return (new_str);
}
int my_unputnbr (unsigned intnb)
Definition at line 13 of file my_unputnbr.c.
References my_putchar().
Referenced by my_rev_unint_tab(), and my_unputnbrs().
{
  unsigned int div;
  int i;
  i = 0;
  div = 1;
  while (div < 1000000000 && nb / (div * 10) > 0)
    div = div * 10;
  while (div != 0)
    {
      if (div == 1)
    my_putchar(nb % 10 + 48);
      else
    my_putchar(nb / div + 48);
      i++;
      nb = nb % div;
      div = div / 10;
    }
  return (i);
}
int my_unputnbrnoaffich (unsigned intnb)
Definition at line 35 of file my_unputnbr.c.
Referenced by my_unputnbrs().
{
  int div;
  int i;
  i = 0;
  div = 1;
  while (div < 1000000000 && nb / (div * 10) > 0)
    div = div * 10;
  while (div != 0)
    {
      i++;
      nb = nb % div;
      div = div / 10;
    }
  return (i);
}
int my_unputnbrs (unsigned intnb, intp, intnbr)
Definition at line 53 of file my_unputnbr.c.
References my_putchar(), my_unputnbr(), and my_unputnbrnoaffich().
Referenced by case_u().
{
  int i;
  int ret;
  int r;
  r = 0;
  ret = 0;
  if (p == 1)
    {
      i = my_unputnbrnoaffich(nb);
      while (nbr > i)
        {
          my_putchar('0');
          nbr--;
          r++;
        }
    }
  ret = r;
  r = my_unputnbr(nb);
  r = ret + r;
  return (r);
}
char** my_word_in_tab (char *str)
Definition at line 83 of file my_word_in_tab.c.
References s_win::i, s_win::j, my_word_in_tab_base(), s_win::nb, and s_win::word.
{
  int i;
  int word;
  t_win struc;
  i = 0;
  word = 1;
  struc.j = 0;
  struc.i = 0;
  struc.nb = 0;
  while (str[i])
    {
      if (str[i] == ' ')
        {
          i++;
          word++;
          while (str[i] == ' ')
            i++;
        }
      else
        i++;
    }
  struc.word = word;
  return (my_word_in_tab_base(str, &struc));
}
int s_putstr (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 13 of file case_printf_part1.c.
References convert_base_deci_octal(), and my_putchar().
Referenced by my_printf().
{
  int i;
  char *str;
  (void)*s;
  (void)*format;
  (void)*tab;
  str = argv;
  i = 0;
  while (str[i])
    {
      if (str[i] < 32 || str[i] >= 127)
    convert_base_deci_octal(str[i], "01234567");
      else
    my_putchar(str[i]);
      i++;
    }
  return (i);
}
char* stat_in_buff (char *strtbuffer, char *buffer, t_getline *s, char *dest)
Definition at line 55 of file get_next_line.c.
References my_gstrcpy(), s_getline::s, SIZE_OF_READ, s_getline::stop, and where_my_buff_end().
Referenced by get_next_line().
{
  int j;
  static char stockstat[SIZE_OF_READ + 1];
  j = 0;
  s->s = 0;
  my_gstrcpy(buffer, stockstat, s, dest);
  while (j != SIZE_OF_READ && s->stop != 1)
    {
      buffer[s->s] = statbuffer[j];
      if (buffer[s->s] == '\n')
    {
      s->stop = 1;
      where_my_buff_end(statbuffer, stockstat, j);
      buffer[s->s] = '\0';
    }
      else
    buffer[s->s + 1] = '\0';
      s->s++;
      j++;
    }
  return (buffer);
}
void where_my_buff_end (char *statbuffer, char *stockstat, intj)
Definition at line 15 of file get_next_line.c.
Referenced by stat_in_buff().
{
  int i;
  i = 0;
  while (statbuffer[j + 1])
    {
      stockstat[i] = statbuffer[j + 1];
      i++;
      j++;
    }
  stockstat[i] = '\0';
}
int x_case (void *argv, t_index *s, const char *format, const t_struc *tab)
Definition at line 62 of file case_printf_part2.c.
References convert_base_deci_16_lun(), convert_base_deci_16_un(), and s_index::p.
Referenced by my_printf().
{
  long n;
  int r;
  (void)*tab;
  (void)*s;
  (void)*format;
  n = (long)argv;
  if (s->p == 2)
    r = convert_base_deci_16_lun((long unsigned int)n, "0123456789ABCDEF");
  else
    r = convert_base_deci_16_un((unsigned int)n, "0123456789ABCDEF");
  return (r);
}
Author
Generated automatically by Doxygen for myhs from the source code.