lib/my/src/printf/my_putnbr.c
NAME
lib/my/src/printf/my_putnbr.c -
SYNOPSIS
#include 'my.h'
Functions
int my_putnbr (int nb)
int my_putnbrnoaffich (int nb)
int my_putnbrs (int nb, int p, int nbr)
int my_lunputnbr (long unsigned int nb)
Function Documentation
int my_lunputnbr (long unsigned intnb)
Definition at line 91 of file my_putnbr.c.
References my_putchar().
Referenced by case_u(), and my_rev_lunint_tab().
{
  long int div;
  int i;
  i = 0;
  div = 1;
  while (nb / (div * 10) > 0)
    div = div * 10;
  while (div != 0)
    {
      if (div == 1)
        my_putchar(nb % 10 + 48);
      else
        my_putchar(nb / div + 48);
      i++;
      nb = nb % div;
      div = div / 10;
    }
  return (i);
}
int my_putnbr (intnb)
Definition at line 13 of file my_putnbr.c.
References my_putchar().
Referenced by my_prompt(), my_putnbrs(), and my_rev_int_tab().
{
  int div;
  int i;
  i = 0;
  div = 1;
  if (nb < 0)
    {
      my_putchar('-');
      nb = - nb;
      i++;
    }
  while (div < 1000000000 && nb / (div * 10) > 0)
    div = div * 10;
  while (div != 0)
    {
      if (div == 1)
    my_putchar(nb % 10 + 48);
      else
    my_putchar(nb / div + 48);
      i++;
      nb = nb % div;
      div = div / 10;
    }
  return (i);
}
int my_putnbrnoaffich (intnb)
Definition at line 41 of file my_putnbr.c.
References my_putchar().
Referenced by my_putnbrs().
{
  int div;
  int i;
  i = 0;
  div = 1;
  if (nb < 0)
    {
      my_putchar('-');
      nb = - nb;
      i++;
    }
  while (div < 1000000000 && nb / (div * 10) > 0)
    div = div * 10;
  while (div != 0)
    {
      nb = nb % div;
      div = div / 10;
      i++;
    }
  return (i);
}
int my_putnbrs (intnb, intp, intnbr)
Definition at line 65 of file my_putnbr.c.
References my_putchar(), my_putnbr(), and my_putnbrnoaffich().
Referenced by case_di().
{
  int i;
  int ret;
  int r;
  r = 0;
  ret = 0;
  if (p == 1)
    {
      i = my_putnbrnoaffich(nb);
      if (nb < 0)
    nb = - nb;
      while (nbr > i)
    {
      my_putchar('0');
      nbr--;
      r++;
    }
    }
  ret = r;
  r = my_putnbr(nb);
  r = ret + r;
  return (r);
}
Author
Generated automatically by Doxygen for myhs from the source code.