lib/my/src/printf/my_putstr.c
NAME
lib/my/src/printf/my_putstr.c -
SYNOPSIS
#include 'my.h'
Functions
int my_putstr (char *str)
Function Documentation
int my_putstr (char *str)
Definition at line 13 of file my_putstr.c.
References my_putchar().
Referenced by case_s(), case_sharp2(), case_unsetenv(), minishell1(), my_find_pwd(), my_prompt(), my_rev_caract_nimpr(), my_rev_int_tab_long(), and my_unsetenv().
{
  int i;
  i = 0;
  while (str[i])
    {
      my_putchar(str[i]);
      i++;
    }
  return (i);
}
Author
Generated automatically by Doxygen for myhs from the source code.