lib/my/src/str/my_putnstr.c
NAME
lib/my/src/str/my_putnstr.c -
SYNOPSIS
#include 'my.h'
Functions
void my_putnstr (char *str, int nb)
Function Documentation
void my_putnstr (char *str, intnb)
Definition at line 13 of file my_putnstr.c.
References my_putchar(), and my_strlen().
Referenced by my_find_pwd().
{
  int i;
  i = nb;
  if (nb >= my_strlen(str))
    return ;
  while (str[i])
    {
      my_putchar(str[i]);
      i++;
    }
}
Author
Generated automatically by Doxygen for myhs from the source code.