lib/my/src/printf/my_putchar.c
NAME
lib/my/src/printf/my_putchar.c -
SYNOPSIS
#include <unistd.h>
#include 'my.h'
Functions
void my_putchar (char c)
Function Documentation
void my_putchar (charc)
Definition at line 14 of file my_putchar.c.
Referenced by case_c(), case_pres(), case_sharp2(), my_find_pwd(), my_lputnbr(), my_lunputnbr(), my_printf2(), my_prompt(), my_putnbr(), my_putnbrnoaffich(), my_putnbrs(), my_putnstr(), my_putstr(), my_rev_caract_nimpr(), my_rev_int_tab_long(), my_rev_int_tab_un(), my_unputnbr(), my_unputnbrs(), and s_putstr().
{
  write(1, &c, 1);
}
Author
Generated automatically by Doxygen for myhs from the source code.