lib/my/src/printf/my_printf.c
NAME
lib/my/src/printf/my_printf.c -
SYNOPSIS
#include <stdarg.h>
#include 'my.h'
Functions
void my_printf3 (const char *format, va_list ap, t_index *s, const t_struc *tab)
void my_printf2 (const char *format, va_list ap, t_index *s, const t_struc *tab)
int my_printf (const char *format,...)
Function Documentation
int my_printf (const char *format, ...)
Definition at line 57 of file my_printf.c.
References case_b(), case_c(), case_di(), case_l(), case_o(), case_p(), case_pres(), case_s(), case_sharp(), case_u(), case_x(), case_zero(), s_index::i, my_printf2(), s_index::p, s_index::r, s_putstr(), and x_case().
Referenced by my_aff_env().
{
  va_list ap;
  t_index s;
  static const t_struc tab[] = { { 's', &case_s }, { 'p', &case_p },
                  { 'd', &case_di },
              { 'b', &case_b }, { 'x', &case_x }, { 'S', &s_putstr },
              { 'X', &x_case }, { 'u', &case_u }, { 'i', &case_di },
              { 'o', &case_o }, { 'c', &case_c }, { '%', &case_pres },
              { '#', &case_sharp }, { '0', &case_zero }, { 'l', &case_l } };
  s.i = 0;
  s.r = 0;
  s.p = 0;
  va_start(ap, format);
  my_printf2(format, ap, &s, tab);
  va_end(ap);
  return (s.r);
}
void my_printf2 (const char *format, va_listap, t_index *s, const t_struc *tab)
Definition at line 34 of file my_printf.c.
References s_index::i, my_printf3(), my_putchar(), s_index::n, s_index::nb, and s_index::r.
Referenced by my_printf().
{
  while (format[s->i])
    {
      s->n = 0;
      s->nb = 0;
      if (format[s->i] == '%')
    {
      s->i++;
      while (format[s->i] == ' ')
        s->i++;
      my_printf3(format, ap, s, tab);
    }
      else
    {
      my_putchar(format[s->i]);
      s->r++;
    }
      s->i++;
    }
}
void my_printf3 (const char *format, va_listap, t_index *s, const t_struc *tab)
Definition at line 14 of file my_printf.c.
References s_struc::c, s_index::i, s_index::n, s_struc::ptr_tab, s_index::r, and s_index::res.
Referenced by my_printf2().
{
  while (tab[s->n].c != format[s->i])
    {
      s->n++;
      if (s->n > 15)
    {
      s->i--;
      break;
    }
    }
  if (s->n <= 15)
    {
      s->res = s->r;
      s->r = (*tab[s->n].ptr_tab)(va_arg(ap, void *), s, format, tab);
      s->r = s->res + s->r;
    }
}
Author
Generated automatically by Doxygen for myhs from the source code.