lib/my/src/str/my_strncmp.c
NAME
lib/my/src/str/my_strncmp.c -
SYNOPSIS
Functions
int my_strncmp (char *a, char *b, int nb)
Function Documentation
int my_strncmp (char *a, char *b, intnb)
Definition at line 11 of file my_strncmp.c.
Referenced by case_unsetenv(), my_find_pwd(), and my_unsetenv().
{
  int i;
  i = 0;
  while (a[i] != '\0' && b[i] != '\0' && i != nb)
    {
      if (a[i] == b[i])
    i++;
      else
    return (1);
    }
  return (0);
}
Author
Generated automatically by Doxygen for myhs from the source code.