.TH "lib/my/src/str/my_strnscpy.c" 3 "Wed Jan 7 2015" "Version 1.0" "myhs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/src/str/my_strnscpy.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'my\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "char * \fBmy_strnscpy\fP (char *dest, char *src, int nb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "char* my_strnscpy (char *dest, char *src, intnb)"

.PP
Definition at line 13 of file my_strnscpy\&.c\&.
.PP
Referenced by my_strnsdup()\&.
.PP
.nf
14 {
15   int   i;
16   int   j;
17 
18   j = 0;
19   i = nb;
20   while (src[i] != '\0')
21     {
22       dest[j] = src[i];
23       i++;
24       j++;
25     }
26   dest[j] = '\0';
27   return (dest);
28 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for myhs from the source code\&.
