.TH "lib/my/src/str/my_strcmp.c" 3 "Wed Jan 7 2015" "Version 1.0" "myhs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/my/src/str/my_strcmp.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'my\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmy_strcmp\fP (char *a, char *b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int my_strcmp (char *a, char *b)"

.PP
Definition at line 13 of file my_strcmp\&.c\&.
.PP
Referenced by case_unsetenv(), and minishell1()\&.
.PP
.nf
14 {
15   while (((*a) != '\0' && (*b) != '\0'))
16     {
17       if (*(a) == *(b))
18         {
19           a++;
20           b++;
21         }
22       else
23         break ;
24     }
25   return ((int) ((*a) - (*b)));
26 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for myhs from the source code\&.
