lib/my/src/printf/my_unputnbr.c
NAME
lib/my/src/printf/my_unputnbr.c -
SYNOPSIS
#include 'my.h'
Functions
int my_unputnbr (unsigned int nb)
int my_unputnbrnoaffich (unsigned int nb)
int my_unputnbrs (unsigned int nb, int p, int nbr)
int my_lputnbr (long int nb)
Function Documentation
int my_lputnbr (long intnb)
Definition at line 77 of file my_unputnbr.c.
References my_putchar().
Referenced by case_di().
{
  long int div;
  int i;
  i = 0;
  div = 1;
  if (nb < 0)
    {
      my_putchar('-');
      nb = - nb;
      i++;
    }
  while (nb / (div * 10) > 0)
    div = div * 10;
  while (div != 0)
    {
      if (div == 1)
    my_putchar(nb % 10 + 48);
      else
    my_putchar(nb / div + 48);
      i++;
      nb = nb % div;
      div = div / 10;
    }
  return (i);
}
int my_unputnbr (unsigned intnb)
Definition at line 13 of file my_unputnbr.c.
References my_putchar().
Referenced by my_rev_unint_tab(), and my_unputnbrs().
{
  unsigned int div;
  int i;
  i = 0;
  div = 1;
  while (div < 1000000000 && nb / (div * 10) > 0)
    div = div * 10;
  while (div != 0)
    {
      if (div == 1)
    my_putchar(nb % 10 + 48);
      else
    my_putchar(nb / div + 48);
      i++;
      nb = nb % div;
      div = div / 10;
    }
  return (i);
}
int my_unputnbrnoaffich (unsigned intnb)
Definition at line 35 of file my_unputnbr.c.
Referenced by my_unputnbrs().
{
  int div;
  int i;
  i = 0;
  div = 1;
  while (div < 1000000000 && nb / (div * 10) > 0)
    div = div * 10;
  while (div != 0)
    {
      i++;
      nb = nb % div;
      div = div / 10;
    }
  return (i);
}
int my_unputnbrs (unsigned intnb, intp, intnbr)
Definition at line 53 of file my_unputnbr.c.
References my_putchar(), my_unputnbr(), and my_unputnbrnoaffich().
Referenced by case_u().
{
  int i;
  int ret;
  int r;
  r = 0;
  ret = 0;
  if (p == 1)
    {
      i = my_unputnbrnoaffich(nb);
      while (nbr > i)
        {
          my_putchar('0');
          nbr--;
          r++;
        }
    }
  ret = r;
  r = my_unputnbr(nb);
  r = ret + r;
  return (r);
}
Author
Generated automatically by Doxygen for myhs from the source code.