lib/my/src/str/my_word_in_tab.c
NAME
lib/my/src/str/my_word_in_tab.c -
SYNOPSIS
#include <stdlib.h>
#include 'my.h'
Functions
int my_pstrlen (char *str)
void my_freetab (char **tab, int lines)
char ** loop_condition (char **tab, t_win *wit, char *str)
char ** my_word_in_tab_base (char *str, t_win *wit)
char ** my_word_in_tab (char *str)
Function Documentation
char** loop_condition (char **tab, t_win *wit, char *str)
Definition at line 39 of file my_word_in_tab.c.
References s_win::i, s_win::j, and s_win::nb.
Referenced by my_word_in_tab_base().
{
  if (str[wit->nb] == ' ')
    {
      tab[wit->i][wit->j] = '\0';
      wit->i++;
      wit->nb++;
      wit->j = 0;
    }
  else
    {
      tab[wit->i][wit->j] = str[wit->nb];
      wit->nb++;
      wit->j++;
    }
  return (tab);
}
void my_freetab (char **tab, intlines)
Definition at line 26 of file my_word_in_tab.c.
{
  int i;
  i = 0;
  while (i < lines)
    {
      free(tab[i]);
      i++;
    }
  free(tab);
}
int my_pstrlen (char *str)
Definition at line 14 of file my_word_in_tab.c.
Referenced by my_word_in_tab_base().
{
  int i;
  i = 0;
  while (str[i] != ' ' && str[i] != '\0')
    i++;
  if (str[i] != '\0')
    i++;
  return (i);
}
char** my_word_in_tab (char *str)
Definition at line 83 of file my_word_in_tab.c.
References s_win::i, s_win::j, my_word_in_tab_base(), s_win::nb, and s_win::word.
{
  int i;
  int word;
  t_win struc;
  i = 0;
  word = 1;
  struc.j = 0;
  struc.i = 0;
  struc.nb = 0;
  while (str[i])
    {
      if (str[i] == ' ')
        {
          i++;
          word++;
          while (str[i] == ' ')
            i++;
        }
      else
        i++;
    }
  struc.word = word;
  return (my_word_in_tab_base(str, &struc));
}
char** my_word_in_tab_base (char *str, t_win *wit)
Definition at line 57 of file my_word_in_tab.c.
References s_win::i, s_win::j, s_win::lines, loop_condition(), my_pstrlen(), s_win::nb, and s_win::word.
Referenced by my_word_in_tab().
{
  char **tab;
  tab = malloc((wit->word + 1) * sizeof(char **));
  if (tab == NULL)
    return (NULL);
  while (wit->word)
    {
      tab[wit->i] = malloc((my_pstrlen(&str[wit->nb]) + 1) * sizeof(char *));
      if (tab[wit->i] == NULL)
    return (NULL);
      wit->nb = wit->nb + my_pstrlen(&str[wit->nb]);
      wit->word--;
      wit->i++;
    }
  tab[wit->i] = NULL;
  wit->lines = wit->i;
  wit->nb = 0;
  wit->i = 0;
  while (str[wit->nb])
    tab = loop_condition(tab, wit, str);
  tab[wit->i][wit->j] = '\0';
  return (tab);
}
Author
Generated automatically by Doxygen for myhs from the source code.