src/mysh.c
NAME
src/mysh.c -
SYNOPSIS
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <signal.h>
#include 'my.h'
#include 'mysh.h'
Functions
int my_unsetenv (char *name, char **env)
void my_find_pwd (char **env)
int case_unsetenv (char *c, char **env)
int case_exit (char **env)
int case_env (char **env)
int case_pwd (char **env)
int minishell1 (char **env)
void my_prompt ()
Function Documentation
int case_env (char **env)
Definition at line 100 of file mysh.c.
References my_aff_env().
Referenced by minishell1().
{
  my_aff_env(env);
  return (0);
}
int case_exit (char **env)
Definition at line 94 of file mysh.c.
Referenced by minishell1().
{
  (void)env;
  return (1);
}
int case_pwd (char **env)
Definition at line 106 of file mysh.c.
References my_find_pwd().
Referenced by minishell1().
{
  my_find_pwd(env);
  return (0);
}
int case_unsetenv (char *c, char **env)
Definition at line 72 of file mysh.c.
References my_putstr(), my_strcmp(), my_strncmp(), my_strnsdup(), and my_unsetenv().
Referenced by minishell1().
{
  if (my_strncmp(c, "unsetenv", 8) == 0)
    {
      if (my_strcmp(c, "unsetenv") == 0)
    {
      my_putstr("Usage : unsetenv <env name>\n");
      return (0);
    }
      else if (c[8] == ' ')
    {
      if (my_unsetenv(my_strnsdup(c, 9), env) == - 1)
        {
          my_putstr("unsetenv error\n");
          return (1);
        }
      return (0);
    }
    }
  return (2);
}
int minishell1 (char **env)
Definition at line 112 of file mysh.c.
References case_env(), case_exit(), case_pwd(), case_unsetenv(), get_next_line(), my_putstr(), and my_strcmp().
Referenced by main().
{
  static const t_ptrtab tab[] =
    {
      { "exit", &case_exit },
      { "env", &case_env },
      { "pwd", &case_pwd },
    };
  char *c;
  int i;
  int ret;
  i = 0;
  if ((c = get_next_line(0)) == NULL)
    return (1);
  if ((ret = case_unsetenv(c, env)) == 1)
    return (1);
  else if (ret == 0)
    return (0);
  while (i != 3 && my_strcmp(c, tab[i].str) != 0)
    i++;
  if (i >= 3)
    {
      my_putstr(c);
      my_putstr(": command not found\n");
    }
  else
    if (tab[i].ptr_tab(env) == 1)
      return (1);
  return (0);
}
void my_find_pwd (char **env)
Definition at line 56 of file mysh.c.
References my_putchar(), my_putnstr(), my_putstr(), and my_strncmp().
Referenced by case_pwd().
{
  int i;
  i = 0;
  while (env[i] != NULL && my_strncmp(env[i], "PWD", 3) == 1)
    i++;
  if (env[i] == NULL)
    my_putstr("/home\n");
  else
    {
      my_putnstr(env[i], 4);
      my_putchar('\n');
    }
}
void my_prompt ()
Definition at line 144 of file mysh.c.
References my_putchar(), my_putnbr(), and my_putstr().
Referenced by main().
{
  static int size = 1;
  my_putstr("$>");
  my_putnbr(size);
  my_putchar(' ');
  size++;
}
int my_unsetenv (char *name, char **env)
Definition at line 35 of file mysh.c.
References my_putstr(), and my_strncmp().
Referenced by case_unsetenv().
{
  int i;
  int x;
  i = 0;
  my_putstr(name);
  while (env[i] != 0)
    {
      x = 0;
      while (env[i][x] != '=' && env[i][x] != '\0')
    ++x;
      if (my_strncmp(env[i], name, x) == 0)
    {
    }
      ++i;
    }
  return (0);
}
Author
Generated automatically by Doxygen for myhs from the source code.