include/mysh.h
NAME
include/mysh.h -
SYNOPSIS
Data Structures
struct s_ptrtab
Typedefs
typedef struct s_ptrtab t_ptrtab
Functions
char * get_next_line (const int fd)
void my_prompt ()
int minishell1 (char **env)
void my_aff_env (char **env)
Typedef Documentation
typedef struct s_ptrtab		 t_ptrtab
Function Documentation
char* get_next_line (const intfd)
Definition at line 81 of file get_next_line.c.
References s_getline::buffer, s_getline::dest, s_getline::i, s_getline::ret, SIZE_OF_READ, stat_in_buff(), and s_getline::stop.
{
  static char statbuffer[SIZE_OF_READ + 1];
  t_getline s;
  s.i = 1;
  s.stop = 0;
  while (s.stop == 0)
    {
      if ((s.buffer = malloc(SIZE_OF_READ * s.i + SIZE_OF_READ)) == NULL)
    return (NULL);
      if ((s.ret = read(fd, statbuffer, SIZE_OF_READ)) == - 1)
    return (NULL);
      statbuffer[s.ret] = '\0';
      s.buffer = stat_in_buff(statbuffer, s.buffer, &s, s.dest);
      if (s.i != 1)
    free(s.dest);
      if (s.ret == 0)
    {
      close(fd);
      return (s.buffer);
    }
      s.dest = s.buffer;
      s.i++;
    }
  return (s.buffer);
}
int minishell1 (char **env)
Definition at line 112 of file mysh.c.
References case_env(), case_exit(), case_pwd(), case_unsetenv(), get_next_line(), my_putstr(), and my_strcmp().
Referenced by main().
{
  static const t_ptrtab tab[] =
    {
      { "exit", &case_exit },
      { "env", &case_env },
      { "pwd", &case_pwd },
    };
  char *c;
  int i;
  int ret;
  i = 0;
  if ((c = get_next_line(0)) == NULL)
    return (1);
  if ((ret = case_unsetenv(c, env)) == 1)
    return (1);
  else if (ret == 0)
    return (0);
  while (i != 3 && my_strcmp(c, tab[i].str) != 0)
    i++;
  if (i >= 3)
    {
      my_putstr(c);
      my_putstr(": command not found\n");
    }
  else
    if (tab[i].ptr_tab(env) == 1)
      return (1);
  return (0);
}
void my_aff_env (char **env)
Definition at line 14 of file my_aff_env.c.
References my_printf().
Referenced by case_env().
{
  int i;
  i = 0;
  while (env[i] != 0)
    {
      my_printf("%s\n", env[i]);
      ++i;
    }
}
void my_prompt ()
Definition at line 144 of file mysh.c.
References my_putchar(), my_putnbr(), and my_putstr().
Referenced by main().
{
  static int size = 1;
  my_putstr("$>");
  my_putnbr(size);
  my_putchar(' ');
  size++;
}
Author
Generated automatically by Doxygen for myhs from the source code.