.TH "s_getline" 3 "Wed Jan 7 2015" "Version 1.0" "myhs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_getline \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <my\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBstop\fP"
.br
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "int \fBret\fP"
.br
.ti -1c
.RI "int \fBs\fP"
.br
.ti -1c
.RI "char * \fBdest\fP"
.br
.ti -1c
.RI "char * \fBbuffer\fP"
.br
.ti -1c
.RI "int \fBerrgest\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 153 of file my\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char* buffer"

.PP
Definition at line 160 of file my\&.h\&.
.PP
Referenced by get_next_line()\&.
.SS "char* dest"

.PP
Definition at line 159 of file my\&.h\&.
.PP
Referenced by get_next_line()\&.
.SS "int errgest"

.PP
Definition at line 161 of file my\&.h\&.
.SS "int i"

.PP
Definition at line 156 of file my\&.h\&.
.PP
Referenced by get_next_line(), and my_gstrcpy()\&.
.SS "int ret"

.PP
Definition at line 157 of file my\&.h\&.
.PP
Referenced by get_next_line()\&.
.SS "int s"

.PP
Definition at line 158 of file my\&.h\&.
.PP
Referenced by my_gstrcpy(), and stat_in_buff()\&.
.SS "int stop"

.PP
Definition at line 155 of file my\&.h\&.
.PP
Referenced by get_next_line(), and stat_in_buff()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for myhs from the source code\&.
