.TH "s_index" 3 "Wed Jan 7 2015" "Version 1.0" "myhs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_index \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <my\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "int \fBn\fP"
.br
.ti -1c
.RI "int \fBnb\fP"
.br
.ti -1c
.RI "int \fBr\fP"
.br
.ti -1c
.RI "int \fBres\fP"
.br
.ti -1c
.RI "int \fBp\fP"
.br
.ti -1c
.RI "int \fBnbr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 40 of file my\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int i"

.PP
Definition at line 42 of file my\&.h\&.
.PP
Referenced by case_l(), case_sharp(), case_sharp2(), case_zero(), my_printf(), my_printf2(), and my_printf3()\&.
.SS "int n"

.PP
Definition at line 43 of file my\&.h\&.
.PP
Referenced by case_l(), case_sharp(), case_sharp2(), case_zero(), my_printf2(), and my_printf3()\&.
.SS "int nb"

.PP
Definition at line 44 of file my\&.h\&.
.PP
Referenced by my_printf2()\&.
.SS "int nbr"

.PP
Definition at line 48 of file my\&.h\&.
.PP
Referenced by case_di(), case_u(), and case_zero()\&.
.SS "int p"

.PP
Definition at line 47 of file my\&.h\&.
.PP
Referenced by case_di(), case_l(), case_o(), case_u(), case_x(), case_zero(), my_printf(), and x_case()\&.
.SS "int r"

.PP
Definition at line 45 of file my\&.h\&.
.PP
Referenced by my_printf(), my_printf2(), and my_printf3()\&.
.SS "int res"

.PP
Definition at line 46 of file my\&.h\&.
.PP
Referenced by my_printf3()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for myhs from the source code\&.
