.TH "s_ptrtab" 3 "Wed Jan 7 2015" "Version 1.0" "myhs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_ptrtab \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mysh\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBstr\fP"
.br
.ti -1c
.RI "int(* \fBptr_tab\fP )(char **env)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 14 of file mysh\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int(* ptr_tab)(char **env)"

.PP
Definition at line 17 of file mysh\&.h\&.
.SS "char* str"

.PP
Definition at line 16 of file mysh\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for myhs from the source code\&.
