s_struc
NAME
s_struc -
SYNOPSIS
#include <my.h>
Data Fields
char c
int(* ptr_tab )(void *argv, t_index *s, const char *format, const struct s_struc *tab)
Detailed Description
Definition at line 51 of file my.h.
Field Documentation
char c
Definition at line 53 of file my.h.
Referenced by case_l(), case_sharp2(), case_zero(), and my_printf3().
int(* ptr_tab)(void *argv, t_index *s, const char *format, const struct s_struc *tab)
Definition at line 54 of file my.h.
Referenced by case_l(), case_sharp(), case_zero(), and my_printf3().
Author
Generated automatically by Doxygen for myhs from the source code.