.TH "s_struc" 3 "Wed Jan 7 2015" "Version 1.0" "myhs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_struc \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <my\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char \fBc\fP"
.br
.ti -1c
.RI "int(* \fBptr_tab\fP )(void *argv, \fBt_index\fP *s, const char *format, const struct \fBs_struc\fP *tab)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file my\&.h\&.
.SH "Field Documentation"
.PP 
.SS "char c"

.PP
Definition at line 53 of file my\&.h\&.
.PP
Referenced by case_l(), case_sharp2(), case_zero(), and my_printf3()\&.
.SS "int(* ptr_tab)(void *argv, \fBt_index\fP *s, const char *format, const struct \fBs_struc\fP *tab)"

.PP
Definition at line 54 of file my\&.h\&.
.PP
Referenced by case_l(), case_sharp(), case_zero(), and my_printf3()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for myhs from the source code\&.
