.TH "s_win" 3 "Wed Jan 7 2015" "Version 1.0" "myhs" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_win \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <my\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBi\fP"
.br
.ti -1c
.RI "int \fBnb\fP"
.br
.ti -1c
.RI "int \fBj\fP"
.br
.ti -1c
.RI "int \fBword\fP"
.br
.ti -1c
.RI "int \fBlines\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 134 of file my\&.h\&.
.SH "Field Documentation"
.PP 
.SS "int i"

.PP
Definition at line 136 of file my\&.h\&.
.PP
Referenced by loop_condition(), my_spe_in_tab(), my_word_in_tab(), and my_word_in_tab_base()\&.
.SS "int j"

.PP
Definition at line 138 of file my\&.h\&.
.PP
Referenced by loop_condition(), my_spe_in_tab(), my_word_in_tab(), and my_word_in_tab_base()\&.
.SS "int lines"

.PP
Definition at line 140 of file my\&.h\&.
.PP
Referenced by my_word_in_tab_base()\&.
.SS "int nb"

.PP
Definition at line 137 of file my\&.h\&.
.PP
Referenced by loop_condition(), my_spe_in_tab(), my_word_in_tab(), and my_word_in_tab_base()\&.
.SS "int word"

.PP
Definition at line 139 of file my\&.h\&.
.PP
Referenced by my_spe_in_tab(), my_word_in_tab(), and my_word_in_tab_base()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for myhs from the source code\&.
